namespace o2.Editor.Tools.HierarchyHighlighter
{
// Generated by o2 Script Generator
 public enum TagEnumAutoGenerated
{
	Untagged,
	Respawn,
	Finish,
	EditorOnly,
	MainCamera,
	Player,
	GameController,
	Highlighted,
	Networked,
	RPC,
	Scripted,
	ClientOnly,
	ServerOnly
}
}
