using o2.EditorTools.o2_Editor;
using o2.EditorTools.o2_Editor.QuickFab;
using o2.EditorTools.Validator;
using UnityEngine;
using UnityEngine.Serialization;

namespace o2.EditorTools {
    [CreateAssetMenu(fileName = "o2EditorSettings", menuName = "O2/Editor/TagHighlighter Asset")]
    public class o2EditorDataAsset : ScriptableObject {
        public HierarchyHighlighterAsset HierarchyHighlighter;
        public QuickFabAsset QuickFab;
        public ScriptDraftPreset[] ScriptDrafts;
        public ValidatorOptions ValidatorOptions;
        public SceneUtilityPreset SceneUtility;
        public string AutoGeneratedScriptSavePath = "Plugins/O2/Auto Generated Scripts";
    }
}